### ISSUE TITLE
How does you work differ from NetworkX's read_shp?

### ISSUE THREAD

**Issue by araichev** [caesar0301/python-s2g#4]
Hi there,

I just discovered your project.
It looks similar to NetworkX's [read_shp](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.readwrite.nx_shp.read_shp.html#networkx.readwrite.nx_shp.read_shp) function. 
Could you explain how it differs from that function, maybe in your README?

**Comment by caesar0301** [comment]
I answered your question in README's QA section.

**Comment by araichev** [comment]
Thanks!
